### ISSUE TITLE
log successful publishing of metrics at DEBUG instead of INFO

### ISSUE THREAD

**Issue by frkline** [blacklocus/metrics-cloudwatch#5]
This needs to be specifically excluded in logging configurations to avoid irrelevant recurring messages:
https://github.com/blacklocus/metrics-cloudwatch/blob/master/src/main/java/com/blacklocus/metrics/CloudWatchReporter.java#L235

**Comment by dirkraft** [comment]
Cool. I think I can live with that. Demoting to DEBUG
